name = "TransformerThermalModel"
uuid = "78a786ea-24d2-559f-86cb-30af155150dd"
version = "0.1.0"
authors = ["Stefan de Lange <langestefan@msn.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
Dates = "1.11.0"
ModelingToolkit = "11.14.0"
julia = "1.10"
